### ISSUE TITLE
stream.pause() not compatible with node v0.10?

### ISSUE THREAD

**Issue by askerb** [ruiquelhas/hapi-magic-filter#1]
When uploading a file, the following code in my handler will not put any data in the file, and the 'end' will not be called if I register happy-magic-filter. If I comment out the registration of magic the file will be saved just fine!

var writeStream = fs.createWriteStream(path);
writeStream.on('error', function (err) { 
  server.log('error', err);
});

request.payload.file.pipe(writeStream);

request.payload.file.on('end', function () { 
  reply('file saved');
};

When putting:
request.payload.file.resume();
after the 'end' function, some data was saved to the file, but not all. Is this an incompatibility with streams in node v0.10 and onwards which never calls pause() and resume()?

**Comment by ruiquelhas** [comment]
Sorry for the late reply. There is definitely something wrong happening when the files are parsed (or not) as streams. I'll give it a look.

Thanks.
