### ISSUE TITLE
Malformed JSON response 

### ISSUE THREAD

**Issue by djclarkson** [ruiquelhas/hapi-magic-filter#2]
First let me say thanks for this package and also admit that I'm probably making a noob mistake. Here is my route:

```
server.route({
method: 'POST',
path: '/api/v1/postFile',
config: {

    payload: {
        output: 'stream',
        maxBytes: 209715200,
        parse: true,
        allow: 'multipart/form-data'
    },

    handler: function (request, reply) {
        var data = request.payload;
        if (data.file) {
            var name = data.file.hapi.filename;
            var path = __dirname + "/uploads/" + name;
            var file = fs.createWriteStream(path);

            file.on('error', function (err) { 
                console.error(err) 
            });

            data.file.pipe(file);

            var fileuri = Path.join('http://localhost:3000/api/v1/', name);

            data.file.on('end', function (err) { 
                var ret = {
                    filename: fileuri
                }
                reply(ret);
            })
        }
    }
}
```

});

This works fine until I add payload validation with hapi-magic-filter, where I get a Malformed JSON reply.

   server.register([
    {
        register: require('hapi-magic-filter'),
        options: {
           allowed: ['jpg', 'jpg', 'png']
        } 
    }
    ], function (err) {
    if (err) {
        console.error('Failed to load a plugin:', err);
    }
   });

**Comment by ruiquelhas** [comment]
The package definitely has some issues with streams, I'm currently re-writing it with proper tests to make sure everything works. In any case, I'll be sure to reproduce your issue. Can you please tell me which `hapi` version you're on?

**Comment by djclarkson** [comment]
Thanks would be much appreciated. Using v8.1.0.
